Feat: allow containers to ignore cron
fbrettnich/hcloud-snapshot-as-backup pull request #5
Opened 2022-10-14 15:57 UTC by chessmango

Please let me know if this is useful or you'd rather do things differently, but I'd like to use this on a service like [Google Cloud Run](https://cloud.google.com/run/docs/create-jobs) or [Amazon ECS](https://docs.aws.amazon.com/AmazonECS/latest/userguide/scheduled_tasks.html) as a scheduled task, rather than a cron builtin.

As such I've added support for an extra `EXTERNAL_CRON` envvar, defaulting to false in containers, that when true will just run as normal. I don't write much Python so code may be messy/sub-optimal 😅 but can confirm this works as intended, so can just exit once complete and re-run on an external schedule as with 'normal' crontab.

Aside: thanks for the really cool project! I came across this after upgrading OS versions and running a blind `terraform apply` - the image ID discrepancy forced a resource recreate 🙈 and backups are server-scoped, so goodbye data

2022-10-14 16:26 UTC, fbrettnich commented
Hi @chessmango, great idea

What do you think if we allow `false` in the `CRON` variable to disable the CRON instead of a new variable?

2022-10-14 16:35 UTC, chessmango commented
> What do you think if we allow `false` in the `CRON` variable to disable the CRON instead of a new variable?

Sounds way more elegant :D I've updated and tested, along with readme

2022-10-14 17:30 UTC, fbrettnich requested changes
A few small improvements

2022-10-14 17:30 UTC, fbrettnich commented on README.md
> +Optional: use `--env CRON=false` to schedule outside of the container, especially using services like [Google Cloud Run jobs](https://cloud.google.com/run/docs/create-jobs) or [Amazon ECS scheduled t
```suggestion
Optional: Set `CRON` to `false` to disable CronScheduler in the container and schedule outside of the container, especially using services like [Google Cloud Run jobs](https://cloud.google.com/run/docs/create-jobs) or [Amazon ECS scheduled tasks](https://docs.aws.amazon.com/AmazonECS/latest/userguide/scheduled_tasks.html)
```

2022-10-14 17:30 UTC, fbrettnich commented on snapshot-as-backup.py
> +
```suggestion
        cron_string = os.environ.get('CRON', False)

        if cron_string is False or cron_string.lower() == 'false':
            run()

        else:
            print(f"Starting CronScheduler [{cron_string}]...")
            cron_scheduler = CronScheduler(cron_string)

            while True:
                try:
                    if cron_scheduler.time_for_execution():
                        print("Script is now executed by cron...")
                        run()
                except KeyboardInterrupt:
                    sys.exit(0)
```

2022-10-16 13:06 UTC, fbrettnich requested changes
Please commit the last changes, then everything is fine 😀

2022-10-16 13:06 UTC, fbrettnich commented on snapshot-as-backup.py
> +
```suggestion
```

2022-10-16 13:06 UTC, fbrettnich commented on snapshot-as-backup.py
> +            print(f"Starting CronScheduler [{cron_string}]...")
```suggestion
            print(f"Starting CronScheduler [{cron_string}]...")
            cron_scheduler = CronScheduler(cron_string)
```

2022-10-16 13:06 UTC, fbrettnich commented on README.md
>  Here you can create a cron: [Cron Generator](https://crontab.guru/#0_1_*_*_*)
```suggestion
If you run the script in Docker, a cron may be specified in the environment variables under `CRON`.  
The cron is used to define how often and at which times the script should be executed.  
Optionally, set `CRON` to `false` to disable CronScheduler in the container and schedule outside of the container.  

Here you can create a cron: [Cron Generator](https://crontab.guru/#0_1_*_*_*)  
```

2022-10-16 13:06 UTC, fbrettnich commented on README.md
> +This cron executes the script every day at 1am. Optionally, set `CRON` to `false` to disable CronScheduler in the container and schedule outside of the container
```suggestion
This cron executes the script every day at 1am.  
```

2022-10-17 11:14 UTC, fbrettnich approved these changes

2022-10-17 11:55 UTC, merged